title: 구조론  
email: idfeelme@gujoron.com
description: |
  관계로 세상을 바라본다.
baseurl: ''
url: 'http://gujoron.github.io'
timezone: Asia/Seoul 

repository: gujoron/gujoron.github.io

permalink: /:year/:month/:day/:title/

excerpt_separator: <!--more-->

markdown: kramdown

krandown:
  input: GFM
  highlighter: rouge

gems:
  - jekyll-paginate

paginate: 5
paginate_path: '/page/:num/'

collections:
  authors:
    output: true
    permalink: /authors/:path/
  tags:
    output: true
    permalink: /tags/:path/

defaults:
  - scope:
      path: ''
      type: authors
    values:
      layout: author
  - scope:
      path: ''
      type: tags
    values:
      layout: tag

exclude: [README.md, Gemfile, Gemfile.lock]

keep_files: [assets, files]

author: idfeelme@gmail.com
image: '/assets/images/default_blog_cover.jpg'
asset_url: /assets
#asset_url: //meta-kage.kakaocdn.net/dn/osa/blog/assets
#asset_url: //t1.daumcdn.net/osa/blog/assets
google_analytics:
  ua: 'UA-88371843-1'
facebook:
  app_id: ''
  username: gujoron
twitter:
  username: gujoron
google_plus:
  username: gujoron
github:
  username: gujoron
