# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 구조론 연구소 자료
email: gujoron911@gmail.com
description: > # http://gujoron.com 의 주요 자료를 자동 백업 합니다.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://gujoron.github.io" # the base hostname & protocol for your site
twitter_username: gujoron
github_username:  gujoron

# Build settings
markdown: kramdown


paginate:         5
paginate_path:    '/gangron_2002/page:num'


